# Generated by Django 5.1.4 on 2024-12-15 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers_made', to=settings.AUTH_USER_MODEL)),
                ('seller_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trade_offers', to='cars.car')),
                ('trade_in_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_as_trade', to='cars.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
