# Generated by Django 5.1.4 on 2024-12-16 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='counter_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offers', to='cars.offer'),
        ),
    ]
