# Generated by Django 5.1.4 on 2024-12-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_offer_counter_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('counter_offered', 'Counter Offered')], default='pending', max_length=20),
        ),
    ]
