# Generated by Django 5.1.4 on 2024-12-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_offer_counter_to_alter_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='counter_to',
        ),
        migrations.AddField(
            model_name='offer',
            name='counter_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='counter_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('counter_accepted', 'Counter Accepted'), ('counter_rejected', 'Counter Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
